#pragma once
#ifndef OPERATOR_TOKEN_SYMBOL_H
#define OPERATOR_TOKEN_SYMBOL_H

#define ADDITION_OPERATOR_SYMBOL L'+'
#define SUBTRACTION_OPERATOR_SYMBOL L'-'
#define MULTIPLICATION_OPERATOR_SYMBOL L'*'
#define DIVISION_OPERATOR_SYMBOL L'/'
#define MODULUS_OPERATOR_SYMBOL L'%'

#endif