#pragma once
#ifndef OPERATOR_TOKEN_SYMBOL_H
#define OPERATOR_TOKEN_SYMBOL_H

#define ADDITION_OPERATOR_SYMBOL '+'
#define SUBTRACTION_OPERATOR_SYMBOL '-'
#define MULTIPLICATION_OPERATOR_SYMBOL '*'
#define DIVISION_OPERATOR_SYMBOL '/'
#define MODULUS_OPERATOR_SYMBOL '%'

#endif