#pragma once
#ifndef TOKENTYPES
#define TOKENTYPES

#define INTEGER_TYPE L"INTEGER_TYPE"
#define ADDTION_OPERATOR L"ADDITONAL_OPERATOR"
#define SUBSTRACTION_OEPRATOR L"SUBSTRACTION_OPERATOR"
#define MULITPLICATION_OPERATOR L"MULTIPLICATION_OPERATOR"
#define DIVISION_OPERATOR L"DIVISION_OPERATOR"
#define MODULUS_OPERATOR L"MODULUS_OPERATOR"

#endif // DEBUG

