#pragma once
#ifndef TOKENTYPES
#define TOKENTYPES

#define INTEGER_TYPE "INTEGER_TYPE"
#define ADDTION_OPERATOR "ADDITONAL_OPERATOR"
#define SUBSTRACTION_OEPRATOR "SUBSTRACTION_OPERATOR"
#define MULITPLICATION_OPERATOR "MULTIPLICATION_OPERATOR"
#define DIVISION_OPERATOR "DIVISION_OPERATOR"
#define MODULUS_OPERATOR "MODULUS_OPERATOR"

#endif // DEBUG

