#pragma once
#ifndef TOKEN_TYPE
#define TOKEN_TYPE

namespace PascalInterpreter
{
	#define INTEGER_TYPE "INTEGER_TYPE"
	#define ADDTION_OPERATOR "ADDITONAL_OPERATOR"
	#define SUBSTRACTION_OEPRATOR "SUBSTRACTION_OPERATOR"
	#define MULITPLICATION_OPERATOR "MULTIPLICATION_OPERATOR"
	#define DIVISION_OPERATOR "DIVISION_OPERATOR"
	#define MODULUS_OPERATOR "MODULUS_OPERATOR"
	#define OOET "OUT_OF_EXPRESSION_TOKENS"
}

#endif // DEBUG

